#!/bin/sh
#
# Runs tests using pristene containers. Writes to ./reports/**/*.xml`.

set -e

DIR="$(dirname "$0")"

. "$DIR"/config

DOCKER_COMPOSE="env OVERVIEW_VERSION=$OVERVIEW_VERSION OVERVIEW_INTEGRATION_TESTS_VERSION=$OVERVIEW_INTEGRATION_TESTS_VERSION docker-compose --project-name $DOCKER_COMPOSE_PROJECT_NAME -f $DIR/docker-compose.yml"

$DOCKER_COMPOSE down -v # in case a previous run errored out
$DOCKER_COMPOSE pull
$DOCKER_COMPOSE build --pull

# Run oververview-db-evolution-applier first, so we don't request from
# overview-web too early.
$DOCKER_COMPOSE up -d overview-database
$DOCKER_COMPOSE run overview-db-evolution-applier # upon exit, DB is up-to-date

find "$DIR"/reports -name '*.xml' -exec rm {} \;

# integration-test will end, and one of three things will have happened:
#
# 1. It succeeded -- and wrote to reports/*.xml
# 2. Some tests failed -- they're in reports/*.xml and Jenkins will see them
# 3. There was a catastrophic failure -- there are no reports/*.xml and Jenkins will complain
#
# We'll report the exit code after we `docker-compose down -v`.
set +e
$DOCKER_COMPOSE up \
  --abort-on-container-exit \
  integration-test
EXIT_CODE=$?
set -e

$DOCKER_COMPOSE down -v

exit $EXIT_CODE
